/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#3525cd",
        "on-primary": "#ffffff",
        "primary-container": "#4f46e5",
        "on-primary-container": "#dad7ff",
        "secondary": "#5c5f61",
        "on-secondary": "#ffffff",
        "secondary-container": "#e0e3e5",
        "on-secondary-container": "#626567",
        "background": "#ffffff",
        "on-background": "#131b2e",
        "surface": "#ffffff",
        "on-surface": "#131b2e",
        "surface-variant": "#dae2fd",
        "on-surface-variant": "#464555",
        "outline": "#777587",
        "outline-variant": "#c7c4d8",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "inverse-primary": "#c3c0ff",
        "primary-fixed": "#e2dfff",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary-fixed": "#0f0069",
        "on-primary-fixed-variant": "#3323cc",
        "secondary-fixed": "#e0e3e5",
        "secondary-fixed-dim": "#c4c7c9",
        "on-secondary-fixed": "#191c1e",
        "on-secondary-fixed-variant": "#444749",
        "tertiary": "#7e3000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#a44100",
        "on-tertiary-container": "#ffd2be",
        "tertiary-fixed": "#ffdbcc",
        "tertiary-fixed-dim": "#ffb695",
        "on-tertiary-fixed": "#351000",
        "on-tertiary-fixed-variant": "#7b2f00",
        "surface-bright": "#ffffff",
        "surface-dim": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#ffffff",
        "surface-container": "#ffffff",
        "surface-container-high": "#ffffff",
        "surface-container-highest": "#ffffff",
        "surface-tint": "#4d44e3",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        lg: "1.5rem",
        "margin-mobile": "16px",
        "container-max": "1200px",
        base: "4px",
        xs: "0.25rem",
        md: "1rem",
        sm: "0.5rem",
        gutter: "24px",
        xl: "2rem",
        "2xl": "4rem",
        "margin-desktop": "64px",
        "max-width": "1280px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        geist: ["Geist", "sans-serif"],
      },
    },
  },
  plugins: [],
}
